package routes

import (
	"net/http"

	httpSwagger "github.com/swaggo/http-swagger"
)

type SwaggerConfig struct{}

type SwaggerInterface interface {
	Handler() http.Handler
}

// Constructor of SwaggerConfig extending from SwaggerInterface
func New() SwaggerInterface {
	return &SwaggerConfig{}
}

//	@Summary		Swagger UI endpoint
//	@Description	Swagger UI endpoint
//	@Router			/swagger/{anything} [get]
func (*SwaggerConfig) Handler() http.Handler {
	return httpSwagger.Handler(
		httpSwagger.URL("/swagger/doc.json"), // The endpoint for the JSON generated by swag
	)
}
